---
consul_version: 0.6.3
consul_archive: "consul_{{ consul_version }}_linux_amd64.zip"
consul_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_archive }}"
consul_download_username: ""
consul_download_password: ""
consul_download_folder: /tmp

consul_is_ui: false 
consul_ui_archive: "consul_{{ consul_version }}_web_ui.zip"
consul_ui_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_ui_archive }}"
consul_ui_dir: "{{ consul_home }}/dist"

consul_home: /opt/consul
consul_config_dir: /etc/consul.d
consul_config_file: /etc/consul.conf
consul_config_template: "consul.json.j2"
consul_log_file: /var/log/consul
consul_data_dir: "{{ consul_home }}/data"


consul_binary: consul

consul_user: consul
consul_group: consul

consul_node_name: "{{ inventory_hostname }}"
consul_is_server: false
consul_servers: ['172.26.30.8', '172.26.30.4', '172.26.30.6']

consul_retry_interval: 30s
consul_retry_max: 2

